apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cray-hms-test-development-pvc
spec:
  accessModes:
    - "{{ .Values.schemaAccessMode }}"
  resources:
    requests:
      storage: 1Gi
  storageClassName: "{{ .Values.schemaStorageClass }}"