apiVersion: v2
name: "cray-hms-test-development"
version: 1.0.1
description: "Kubernetes resources for cray-hms-test-development"
home: https://github.com/Cray-HPE/hms-test-charts
sources:
  - https://github.com/Cray-HPE/hms-test
maintainers:
  - name: nieuwsma
dependencies:
  - name: cray-service
    version: "~7.0.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/images: |
    - name: Image that does is ignored when linting
      image: dtr.dev.cray.com/foo:bar
    - name: Image in a private repo
      image: artifactory.algol60.net/csm-docker-private/stable/csm-docker-sle-python:3.10
appVersion: 3.2.0
